---
site:
  title: CRC Documentation
  start_page: ROOT::introducing.adoc
  url: https://crc.dev/docs
  robots: allow
content:
  sources:
    - url: ./ # Point to Git repository
      branches: HEAD # Use local conntent
      edit_url: "https://github.com/crc-org/docs/edit/main/{path}"
      start_path: . # Point to docs content
output:
  clean: true # Delete stale content
  dir: public
runtime:
  cache_dir: .cache/antora # Use a local directory rather than $HOME
  log:
    failure_level: warn # Fail on missing attributes
    level: debug # Extra verbose
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
urls:
  html_extension_style: indexify
  redirect_facility: static
antora:
  extensions:
    - "@antora/lunr-extension"
    - ./extensions/get-versions.js
asciidoc:
  sourcemap: true
  attributes:
    icons: font
    nbsp: "&#160;"
    project-context: crc
    # Platforms
    rh: "Red{nbsp}Hat"
    rhel: "Red{nbsp}Hat Enterprise{nbsp}Linux"
    fed: Fedora
    centos: CentOS
    mac: macOS
    msw: Microsoft Windows
    debian: Debian
    ubuntu: Ubuntu
    openshift: OpenShift
    ocp: OpenShift Container Platform
    okd: OKD
    ushift: MicroShift
    # Product naming
    prod: CRC
    rh-prod: CRC
    bin: crc
    # Documentation naming
    context: crc
    # URLs
    crc-download-url: https://console.redhat.com/openshift/create/local
    openshift-installer-url: https://console.redhat.com/openshift/create
    openshift-docs-url: https://docs.openshift.com/container-platform/latest
    openshift-docs-url-landing-page: "{openshift-docs-url}/welcome/index.html#developer-activities"
    oc-download-url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/
    odo-docs-url: https://odo.dev/docs/introduction
    odo-docs-url-installing: https://odo.dev/docs/overview/installation
    telemetry-notice-url: https://developers.redhat.com/article/tool-data-collection
    rhel-resolved-docs: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/using-different-dns-servers-for-different-domains_configuring-and-managing-networking
